### ISSUE TITLE
Skipped Containers

### ISSUE THREAD

**Issue by holocronology** [Minituff/nautical-backup#25]
First off, this is a great project! I installed it last night and it seems to be running as expected.

As a first question/comment:
The backup is looking at the container name and then trying to find a matching folder in the app/source local directory. So, if I have a container named "Pi.Alert" but my local folder is named "pialert" it will be skipped because it isn't matched. Am I understanding that correctly? So I either need to make the container and local folder names match OR use the override arguments/variables to the effect of:

`OVERRIDE_SOURCE_DIR=Pi.Alert:/localdir/pialert`

OR is it simply:

`OVERRIDE_SOURCE_DIR=Pi.Alert:pialert` (with no pathing, just the name of contatiner:name of folder?)

Do you also need to do that for the destination or does it just then rsync "/localdir/pialert" to the destination?

**Comment by Minituff** [comment]
Hi there, 

Great question. It sounds like you are understanding how it works correctly. The easiest thing to do is rename the container to `pialert` or rename the local folder to `Pi.Alert` so they will match. But if you want to keep the directories and names the way there you could have a few options:


You should be able to use `OVERRIDE_SOURCE_DIR=Pi.Alert:pialert` as long as the `pialert` folder is within the local-source-dir used in the volume mapping like this: `local-source-dir:/app/source`.

[Nautical](https://github.com/Minituff/nautical-backup) will see all the containers within the `/app/source` directory like this:

```properties
<Nautical Backup>/app/source:
 - pialert  # Renamed from Pi.Alert
 - pihole   # Example
 - plex     # Example
```
Then since the `container-name` matches the `directory-name` it should be detected and processed.

---

Additionally, if your `pialert` folder is not withing the local-source-dir you could remap it using the Docker Volumes like this:
```yml
volumes:
  # Standard config
  - /var/run/docker.sock:/var/run/docker.sock
  - /source:/app/source
  - /destination:/app/destination
 
# Alternative source directory for Pi.Alert
  - /your/local/source/path/pialert:/app/source/Pi.Alert  # Remapped to match the container_name Pi.Alert
  
# OR. This option would need to be combined with `OVERRIDE_SOURCE_DIR=Pi.Alert:pialert` 
# since the folder name still wouldn't match the container name
  - /your/local/source/path/pialert:/app/source/pialert 
```

All of these options should get thing working for you!


I am happy to see you using my project. Let me know if this fixes things or go ahead and close the issue if it works.

**Comment by Minituff** [comment]
I also updated the documentation to help clarify how Overrides work a little bit better: https://github.com/Minituff/nautical-backup/pull/29. The changes should be live on the documentation website.
