### ISSUE TITLE
Questions about the general usage

### ISSUE THREAD

**Issue by Kimbaras** [Minituff/nautical-backup#74]
Hey there!

First of all couple of notes about this...

It's not really an "issue" more of a "requesting a clarification" style of request. 
I've seen there is already the "documentation" label.

Also, keep in mind that I went through the docs but haven't started playing with it yet. Planned but didn't have time yet, so maybe my question would be obvious if I tried it already, feel free to bash me on that!

Now the real question: from what I understood this is meant to run on the host where the other containers are running.  
It doesn't have remote backup functionalities right?

My setup is something similar to:

- Main host running Portainer (with a couple of others containers running locally)
- Various VMs / LXC running mainly one or two containers each (I like to keep things separated and allocate the dedicated space and resources to everything... yeah I know, I know)

This tool should be installed on each host, correct?
IF this is the case, would there be the possibility to have a general dashboard which talks with the other containers (agents?) (as Portainer do, basically).

Again, as mentioned I haven't had the time to play with the tool yet, so sorry if this would be very very obvious after having tried it.

Would this be an "ok" addition to the Q&A section on the site?

Thanks!

**Comment by Minituff** [comment]
Hi there @Kimbaras,

Good question; let's dive in.

> this is meant to run on the host where the other containers are running.

Yes, exactly

> This tool should be installed on each host, correct?

Yes, that's also true.

Essentially, Nautical just accesses Docker via the socket you mount with `-v /var/run/docker.sock:/var/run/docker.sock` and then runs `Bash` commands to:
1. Stop the container (if configured)
2. Run the backup via `rsync`
3. Start the container

Because of this, it is only able to access the Docker containers running on the __same machine as the Nautical container itself__. So if you run multiple VMs/LXCs that have unique Docker installations on each of them, then you would need to install Nautical on each one.

> It doesn't have remote backup functionalities right?

No, it doesn't. I decided to not rebuild the features of many existing products. They probably would do it much better than I could anyways lol.

But what you could do (and what I do), is point a [remote backup solution](https://minituff.github.io/nautical-backup/advanced/remote-backups/) (I use Kopia) at the `destination` location for Nautical.
So it would look like this:
1. Nautical backs up the `source` folder to the `nautical-dest` folder
2. Kopia backs up the `nautical-dest` folder to a remote server. 

Nautical __CAN__ backup to an NFS share though, as long as you mount it on the host machine. For example, at my house I run a TrueNAS server and a Proxmox server which runs my containers in a Ubuntu VM. Then I mount the TrueNAS NFS share on my Proxmox VM at `/mnt/nfs/nautical-backup-dest`, then I use that directory as the destination folder for Nautical, like this:
* `-v /mnt/nfs/nautical-backup-dest:/app/destination`

Using this config, I get a *remote* backup from my Proxmox machine to my TrueNAS machine. I have some more detailed steps to set this up in the docs [here](https://minituff.github.io/nautical-backup/advanced/nfs-share/)

> Would this be an "ok" addition to the Q&A section on the site?

I think so, yes. The questions you asked are exactly what I'm trying to figure out how to *explain better* in my docs. At first glance I think it is a little confusing how Nautical works, so I want to add more clarity to *de-mystify* this.

**Comment by Kimbaras** [comment]
Very detailed and clear answers!

All clear on my side and now I have a more clear idea of how this is working (still haven't had the time to play with it tho...)

I believe this could be closed as you answered each of my questions, not sure if you want to keep this open while updating the docs?
If not, feel free to close it!

Thanks again!

**Comment by Minituff** [comment]
Glad to hear it!

I incorporated some of your ideas into the docs with this commit: https://github.com/Minituff/nautical-backup/commit/e4cc2ee6b12eaccd0b94e0c10d439e6180d56b16

Specifically, I updated the [Introduction](https://minituff.github.io/nautical-backup/introduction/) and [Q&A](https://minituff.github.io/nautical-backup/q-and-a/) sections.

Let me know how the installation goes. Feel free to re-open the issue (or make a new one) if you run into any problems or just have questions about fitting Nautical into your network.
